### PR TITLE
Fix build breaks in generated tests

### PR DESCRIPTION
**Pull request by willfaught**
It's probably easier to review commits individually.

### CODE REVIEW

**Comment by willfaught** [comment]
Test results are unchanged.

**Comment by willfaught** [comment]
This is ready for review.

**Comment by willfaught** [comment]
@pboyer @wjkohnen Any takers? :)

**Comment by pboyer** [comment]
Thanks @willfaught!

Can you give a bit more context about what has been changed here? It says "fixes" but the test results are unchanged. Maybe then I can give a better review. :D

**Comment by willfaught** [comment]
Oh sure. I meant fixes in that they address compilation errors I was seeing in the output during a test run. The generated Go code was broken in some cases, some of which I addressed with this.
- `Fix parser tokens in generated Go tests` fixes Parser.Token syntax to be ParserToken.
- `Fix SetErrorHandler and NewBailErrorStrategy calls in generated Go tests` adds `p.` method instance prefixes to those calls
- `Fix Property calls in generated Go tests` changes the calls from methods to funcs (the Property func comes from @members{...}).
- `Clean up Go test templates` just does general code clean up there, miscellaneous stuff, doesn't fix bugs
- `Generate Go tests` generates the Java code for the Go tests to sync it with the above changes

**Comment by willfaught** [comment]
Anything else I can do for this? It addresses problems like these in the test output:

```
parser/t_parser.go:190: undefined: SetErrorHandler
parser/t_parser.go:190: undefined: NewBailErrorStrategy
```

**Comment by pboyer** [comment]
OK - This seems fine. Sorry for the delay!

**Pull request merged**
