### PR TITLE
http:// not allowed in go import path

### PR DESCRIPTION
**Pull request by peter-mcconnell**

### CODE REVIEW

**Comment by willfaught** [comment]
:+1:

**Comment by pboyer** [comment]
Thanks @pemcconnell!

**Comment by willfaught** [comment]
Did they sign the CLA? Sorry, I'm on mobile, can't see at the moment.

**Comment by pboyer** [comment]
@pemcconnell Can you please sign the ANTLR CLA with a follow up PR. I screwed up and forgot to mention it. Otherwise I will need to remove this commit from the history.

**Comment by peter-mcconnell** [comment]
Sure thing - PR attached. Sorry, should have caught this myself. Thanks!

**Pull request merged**
