### PR TITLE
Travis: Update to current stable Go version.

### PR DESCRIPTION
**Pull request by jwkohnen**
Let's pull Go 1.7.3 in travis.

Piggy back comment: Great work guys! I am happy to see the upstream merge going on. If there is need for more hands to fix the merge, please holler me. Recently I took on a new employment and am a little constrained in my time, but I can definitely free a few hours here and there. 

There was a wiki page that listed a few tasks that need to be done before the merge. Do you know where it is?

### CODE REVIEW

**Comment by pboyer** [comment]
@wjkohnen I moved all of the wiki tasks into issues. You can track them here: https://github.com/pboyer/antlr4/projects/1

**Comment by pboyer** [comment]
It's always nice to be on the bleeding edge, although I usually stay back a point release for production projects. @willfaught What do you think?

**Comment by willfaught** [comment]
I usually only do minor versions (like 1.7) unless there's a bug/security patch that affects the project (like a 1.7.x). Otherwise, you're constantly bumping the version to keep up to date with patches.

I'd say it should be 1.7 at least, since most stuff is expected to run against it. For production/stability concerns, we could do both 1.6 and 1.7.

**Comment by pboyer** [comment]
On further thought, I think this is a safe move. The only effect would will be to speed up travis compile/test times.

**Pull request merged**
