### PR TITLE
auto locate go path on the windows

### PR DESCRIPTION
**Pull request by mei-rune**

### CODE REVIEW

**Comment by willfaught** [comment]
@runner-mei Thanks. Did you test it manually? Just need to verify. I'm surprised nothing else has to be done to the path for it to work on Windows. What is the install path on Windows?

**Comment by mei-rune** [comment]
I run fail on the windows, patch this and run ok.

**Comment by pboyer** [comment]
Thanks @runner-mei. I don't have a Windows machine to check this, but I'll trust you. :)

**Comment by pboyer** [comment]
@runner-mei I need you to sign the CLA (contributors.txt) file with a follow up PR. If not, I'll need to manually pull this from the history. This is my fault - sorry for the annoyance.

**Pull request merged**
