### PR TITLE
ATN runtime format, style, and comment cleanup

### PR DESCRIPTION
**Pull request by willfaught**
Just the ATN runtime files for now to get a consensus on the preferred style. Most changes are self-explanatory. The changes that might not be are:
- Consistent style, improved readability, and easier skimming
  - Separate package decls with a blank line except optionally decls in `(...)` blocks
  - Group like-statements together (e.g. const, var, control flow, loop, condition, defer, expression/assignment/inc/dec/send/receive/go/etc.) and separate those groups with a blank line
  - Separate `{...}` and `(...)` blocks with a blank line
  - Group undocumented struct type fields together
  - Separate doc'ed struct type fields with a blank line
  - Order package decls, struct type fields, and interface methods like godoc unless it would be less clear (although I left interface methods, func decls, and method impls alone for now; let me know what you think)
  - Separate cases with a blank line
  - Changed `:=` decls to `var` decls where possible
- Idiomatic
  - Doc comments 
    - No C# syntax
    - Start with the name
    - Refer to params by their code name (e.g. `ctx`, not `context`, if param named `ctx`)
    - Use multiple paragraphs where useful
    - Minor/major rewording to make them understandable full sentences (please double-check these rewordings, I didn't understand some of them, so I took my best guess)
  - Inline comments are full sentences and use sentence case
  - No zero-value initializations and 0-capacity slice initializations
  - Simple, lowercase panic strings with no ending punctuation
- Changed some field assignments to struct literals

I get that everyone has a preferred style, and it might not match with this one. I'm happy to change it to match whatever the consensus is.

Test results are unchanged.

### CODE REVIEW

**Comment by pboyer** [comment]
@willfaught @wjkohnen  A question - should we just remove all of the function/field descriptor comments? They are sparse and largely duplicated in the other runtimes, bound to become out of date/inconsistent...

**Comment by pboyer** [comment]
@willfaught Besides the above philosophical comment, this looks good.

**Comment by willfaught** [comment]
I think it's good practice to document everything exported, but I think you're referring to un-exported things in this case. I think it's helpful to keep comments that help to understand/read the code and don't merely describe what the code says. (IIRC, there's one field doc in this diff that says it's only set after a `readOnly` field; I thought that was helpful. There's another one for a slice field that said it was a set of the slice element type; not as helpful.) I've found that preconditions, postconditions, relationships, context, etc. often make good comments, especially in complex problem domains and types with lots of fields. Useless comments tend to be ignored and tend to rot.

@pboyer is probably in the best position to judge which is which. I kept them all because I don't understand how most of it works at this point. ;) It's probably best addressed in a separate PR.

Edited

**Comment by pboyer** [comment]
Thanks @willfaught!

**Pull request merged**
